### ISSUE TITLE
FileNotFoundError when dealing with a symlink

### ISSUE THREAD

**Issue by Cyber28** [AlexFlipnote/diskspace#2]
When diskspace encounters a symlink, it fails with FileNotFoundError

```➜  ~ diskspace
Traceback (most recent call last):
  File "/usr/bin/diskspace", line 11, in <module>
    load_entry_point('diskspace==1.0.3.2', 'console_scripts', 'diskspace')()
  File "/usr/lib/python3.7/site-packages/diskspace/diskspace.py", line 51, in main
    shell()
  File "/usr/lib/python3.7/site-packages/diskspace/diskspace.py", line 45, in shell
    whitelist=args.only
  File "/usr/lib/python3.7/site-packages/diskspace/pathRender.py", line 140, in pretty_print
    allFiles = self.all_files
  File "/usr/lib/python3.7/site-packages/diskspace/pathRender.py", line 134, in all_files
    return list(self.getPathFiles().values())
  File "/usr/lib/python3.7/site-packages/diskspace/pathRender.py", line 97, in getPathFiles
    size = os.path.getsize(file)
  File "/usr/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '.steampath'```

**Comment by AlexFlipnote** [comment]
Should be resolved now in c12dd39
